- name: Set vars (ESP: Establecer vars)
  set_fact:
    app_type: "{{ app_dir | dirname | basename }}"

- name: Read kubify.yml (ESP: Leer kubify.yml)
  include_vars:
    file: "{{ kubify_yml }}"
    name: kubify_config

- name: Read application port (ESP: Leer el puerto de la aplicación)
  set_fact:
    app_port: "{{ kubify_config | json_query('service.port') | default(8080, true) }}"

- name: Check if package.json exists (ESP: Compruebe si existe package.json)
  stat:
    path: "{{ app_dir}}/package.json"
  register: package_json_file

- name: Check if yarn.lock exists (ESP: Compruebe si existe yarn.lock)
  stat:
    path: "{{ app_dir}}/yarn.lock"
  register: yarn_lock_file

- name: Read package.json (ESP: Leer package.json)
  include_vars:
    file: "{{ app_dir }}/package.json"
    name: package_json
  when: package_json_file.stat.exists

- name: Read app version (ESP: Leer la versión de la aplicación)
  set_fact:
    app_cicd_build_image_version: "{{ package_json | json_query('version') }}"

- name: Read node engine version (ESP: Leer la versión del motor de nodo)
  set_fact:
    package_json_node_version: "{{ package_json | json_query('engines.node') | default('10.15.1', true) }}"

- name: Create kubify work directory (ESP: Crear directorio de trabajo de kubify)
  file:
    path: "{{ app_kubify_dir }}"
    state: directory

- name: Create kubify work manifests directory (ESP: Crear directorio de manifiestos de trabajo de kubify)
  file:
    path: "{{ app_kubify_dir }}/manifests"
    state: directory

- name: Read profile config (ESP: Leer configuración de perfil)
  include_vars:
    file: "{{ app_dir }}/config/config.{{ profile }}.yaml"
    name: profile_config
