---
- name: Update .dockerignore (ESP: Actualizar .dockerignore)
  lineinfile:
    path: "{{ app_dir }}/.dockerignore"
    state: present
    create: yes
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^\*.swp', line: '*.swp' }
    - { regexp: '^/kubify\.yml', line: '/kubify.yml'}
    - { regexp: '^/secrets', line: '/secrets'}
    - { regexp: '^/config', line: '/config'}

- name: Check if project has custom dev Dockerfile (ESP: Compruebe si el proyecto tiene un Dockerfile de desarrollo personalizado)
  stat:
    path: "{{ app_dir }}/Dockerfile.dev"
  register: custom_dev_docker_stat_result

- name: Check if project has custom build Dockerfile (ESP: Compruebe si el proyecto tiene una compilación personalizada de Dockerfile)
  stat:
    path: "{{ app_dir }}/Dockerfile.build"
  register: custom_build_docker_stat_result

- name: Generate Dockerfiles (ESP: Generar Dockerfiles)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "templates/Dockerfile.dev.j2",  dest: "{{ app_kubify_dir }}/Dockerfile.dev" }
    - { src: "templates/Dockerfile.build.j2", dest: "{{ app_kubify_dir }}/Dockerfile.build" }
  when: custom_dev_docker_stat_result.stat.exists == False and custom_build_docker_stat_result.stat.exists == False

- name: Copy Dockerfiles (ESP: Copiar Dockerfiles)
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "{{ app_dir }}/Dockerfile.dev",  dest: "{{ app_kubify_dir }}/Dockerfile.dev" }
    - { src: "{{ app_dir }}/Dockerfile.build", dest: "{{ app_kubify_dir }}/Dockerfile.build" }
  when: custom_dev_docker_stat_result.stat.exists == True and custom_build_docker_stat_result.stat.exists == True

- name: Ensure config directory exists (ESP: Asegúrese de que exista el directorio de configuración)
  file:
    path: "{{ app_dir }}/config/"
    state: directory

- name: Checkout config (ESP: Configuración de pago)
  shell: git checkout {{ app_config_sha }} {{ item }}
  with_items:
    - "{{ app_dir }}/config"
    - "{{ app_dir }}/secrets"
  when: app_config_sha != ""

- name: Generate manifests (ESP: Generar manifiestos)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "templates/skaffold.yaml.j2",         dest: "{{ app_kubify_dir }}/skaffold.yaml" }
    - { src: "templates/deployment.yaml.j2",       dest: "{{ app_manifests }}/deployment.yaml" }
    - { src: "templates/service.yaml.j2",          dest: "{{ app_manifests }}/service.yaml" }
    - { src: "templates/ingress.yaml.j2",          dest: "{{ app_manifests }}/ingress.yaml" }
    - { src: "templates/database.yaml.j2",         dest: "{{ app_manifests }}/database.yaml" }
    - { src: "templates/cron.yaml.j2",             dest: "{{ app_manifests }}/cron.yaml" }
    - { src: "templates/generated-config.yaml.j2", dest: "{{ app_manifests }}/generated-config.yaml" }
  vars:
    app_manifests: "{{ app_kubify_dir }}/manifests"
    manifests_glob:
      - "../../{{ kubify_dir | basename }}/{{ env }}/{{ app_name }}/manifests/*" # skaffold needs a relative path to the manifests
      - "../../{{ app_type }}/{{ app_name }}/config/*.{{ profile }}.yaml"
      - "../../{{ app_type }}/{{ app_name }}/kubify.yml"

- name: Decrypt secrets (ESP: Descifrar secretos)
  shell: "kubesec decrypt {{ item.src }} > {{ item.dest }}"
  with_items:
    - { src: "{{ app_dir }}/../{{ app_name }}/secrets/secrets.{{ profile }}.enc.yaml", dest: "{{ app_kubify_dir }}/manifests/secrets.yaml"}
