---
apiVersion: k8.kubify.local/v1
kind: Config
metadata:
  name: example-django-simple-svc
init: |
  echo "run something (migrations etc) before service deployed here"
  python manage.py makemigrations
  python manage.py migrate
dev:
  sync:
    'app/***': 'app/'
  scripts:
    start: |
      echo 'listening for code changes'
      python manage.py runserver  0.0.0.0:8000
release:
  scripts:
    start: |
      python manage.py runserver  0.0.0.0:8000
config:
  PORT: "8000"
  APP_NAME: example-django-simple-svc
  DEBUG: "example-django-simple-svc:*"
  ENV: "{{ env }}"
  KUBIFY_ENV: "{{ env }}"
profiles:
  dev:
    scaler:
      minReplicas: 2
      maxReplicas: 4
      metrics:
      - type: Resource
        resource:
          name: cpu
          target:
            type: Utilization
            averageUtilization: 40
    resources:
      requests:
        cpu: 64m
        memory: 64Mi
      limits:
        cpu: 128m
        memory: 128Mi
    
