---
apiVersion: k8.kubify.local/v1
kind: Config
metadata:
  name: example-django-simple-svc
init: |
  echo "run something (migrations etc) before service deployed here"
  python manage.py makemigrations
  python manage.py migrate
dev:
  sync:
    'app/***': 'app/'
  scripts:
    start: |
      echo 'listening for code changes'
      python manage.py runserver  0.0.0.0:8000
release:
  scripts:
    start: |
<<<<<<< HEAD
      # gunicorn myproject.wsgi
      python manage.py runserver  0.0.0.0:8000
config:
  PORT: "8000"
  #TODO notice repeating folder name "example-django-simple-svc" (that should be automatic, per the folder name, should be 0 times in this file)
=======
      python manage.py runserver  0.0.0.0:8000
config:
  PORT: "8000"
>>>>>>> d8da54d3c115413db69f39b2c1043ffcf9ea242e
  APP_NAME: example-django-simple-svc
  DEBUG: "example-django-simple-svc:*"
  ENV: "{{ env }}"
  KUBIFY_ENV: "{{ env }}"
profiles:
  dev:
    scaler:
      minReplicas: 2
      maxReplicas: 4
      metrics:
      - type: Resource
        resource:
          name: cpu
<<<<<<< HEAD
          targetAverageUtilization: 40
=======
          target:
            type: Utilization
            averageUtilization: 40
>>>>>>> d8da54d3c115413db69f39b2c1043ffcf9ea242e
    resources:
      requests:
        cpu: 64m
        memory: 64Mi
      limits:
        cpu: 128m
        memory: 128Mi
    
