---
- set_fact:
    dir_dnsmasq: "{{ '/usr/local/etc' if ansible_os_family == 'Darwin' else '/etc/NetworkManager/dnsmasq.d' }}"
    file_dnsmasq: "{{ 'dnsmasq.conf' if ansible_os_family == 'Darwin' else 'kubify-codes' }}"

- name: create NetworkManager dnsmasq config for kubify
  become: yes
  file:
    path: "{{ dir_dnsmasq }}/{{ file_dnsmasq }}"
    state: touch
  when: ansible_os_family == "Debian"

################################################################################
# This part is configured in `kubify install` for Linux
################################################################################
- name: Add *.{{ local_domain }} resolver port
  become: yes
  lineinfile:
    state: present
    line: port 5354
    create: yes
    dest: /etc/resolver/{{ local_domain }}
    owner: root
    group: wheel
  when: ansible_os_family == "Darwin"

- name: Add *.{{ local_domain }} resolver address
  become: yes
  lineinfile:
    state: present
    line: nameserver 127.0.0.1
    create: yes
    dest: /etc/resolver/{{ local_domain }}
    owner: root
    group: wheel
  when: ansible_os_family == "Darwin"

- name: Add listen address config
  become: yes
  lineinfile:
    state: present
    line: listen-address=127.0.0.1
    create: yes
    dest: "{{ dir_dnsmasq }}/{{ file_dnsmasq }}"
    owner: root
    group: wheel
  when: ansible_os_family == "Darwin"

- name: Add listen port config
  become: yes
  lineinfile:
    state: present
    line: port=5354
    create: yes
    dest: "{{ dir_dnsmasq }}/{{ file_dnsmasq }}"
    owner: root
    group: wheel
  when: ansible_os_family == "Darwin"
  #
################################################################################

- name: Remove stale resolver entries for *.{{ local_domain }}
  become: yes
  lineinfile:
    state: absent
    regexp: ^address=/\.{{ local_domain | replace(".", "\.") }}/.*
    create: no
    dest: "{{ dir_dnsmasq }}/{{ file_dnsmasq }}"
  register: config_change_1

- name: Resolve *.{{ local_domain }} to Cluster IP
  become: yes
  lineinfile:
    state: present
    line: address=/.{{ local_domain }}/{{ cluster_ip }}
    create: yes
    dest: "{{ dir_dnsmasq }}/{{ file_dnsmasq }}"
  register: config_change_2

- name: Get dnsmasq PID
  shell: "ps -ef | grep -v grep | grep /dnsmasq | awk '{print $2}'"
  register: running_processes
  when: ansible_os_family == "Darwin"

- name: Kill dnsmasq
  shell: "kill {{ item }}"
  become: yes
  with_items: "{{ running_processes.stdout_lines }}"
  when: ansible_os_family == "Darwin"

- name: Wait for dnsmasq to terminate
  wait_for:
    path: "/proc/{{ item }}/status"
    state: absent
  with_items: "{{ running_processes.stdout_lines }}"
  ignore_errors: yes
  register: killed_processes
  when: ansible_os_family == "Darwin"

- name: Ensure dnsmasq is really killed
  become: yes
  shell: "kill -9 {{ item }}"
  with_items: "{{ killed_processes.results | select('failed') | map(attribute='item') | list }}"
  when: ansible_os_family == "Darwin"

- name: Restart dnsmasq as user (for running)
  become: no
  command: brew services restart dnsmasq
  when: ansible_os_family == "Darwin"

- name: Restart dnsmasq as sudo (to also enable start on boot)
  become: yes
  command: brew services restart dnsmasq
  when: ansible_os_family == "Darwin"

- name: restart NetworkManager (dnsmasq) for Ubuntu
  become: yes
  systemd:
    name: NetworkManager
    state: restarted
  register: dnsmasq_update
  when:
    - ansible_os_family == "Debian"
    - config_change_1.changed or config_change_2.changed

# This tries to open an internet connection for up to 30 seconds before failure.
- name: wait for network connection to come back up
  wait_for:
    host: 8.8.8.8
    port: 53
    timeout: 30
    msg: |
      "Waiting for (up to 30s) for Internet to come back up. Please check"
      "README.md for troubleshooting steps if you see this"
  when: dnsmasq_update.changed
